<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: D:\kn24_php\kn24_php\src\templates\nav.php */
final class Template_95aa10e50f extends Latte\Runtime\Template
{
	public const Source = 'D:\\kn24_php\\kn24_php\\src\\templates\\nav.php';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<?php
?>

<nav class="nav">
    <a href="/" class="nav_link">Головна</a>

    <a href="/game" class="nav_link">Game</a>
    <a href="/fabric" class="nav_link">Fabric.JS</a>

    <?php if(isset($_SESSION[\'login\'])): ?>
        <a href="?logout=1" class="nav_link">Logout</a>
    <?php else: ?>
        <a href="/login" class="nav_link">Login</a>
    <?php endif ?>

</nav>';
	}
}
