<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: D:\kn24_php\kn24_php\src\templates\_nav.latte */
final class Template_fdb272ea6e extends Latte\Runtime\Template
{
	public const Source = 'D:\\kn24_php\\kn24_php\\src\\templates\\_nav.latte';


	public function main(array $ʟ_args): void
	{
		echo '<nav class="nav">
    <a href="/" class="nav_link">Головна</a>
    <a href="/game" class="nav_link">Game</a>
    <a href="/fabric" class="nav_link">Fabric.JS</a>
    <a href="?logout=1" class="nav_link">Logout</a>
    <a href="/login" class="nav_link">Login</a>
</nav>';
	}
}
