<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: D:\kn24_php\kn24_php\src\templates\_footer.latte */
final class Template_b203422c6d extends Latte\Runtime\Template
{
	public const Source = 'D:\\kn24_php\\kn24_php\\src\\templates\\_footer.latte';


	public function main(array $ʟ_args): void
	{
		echo '<footer>
    <p>&copy; ';
		echo LR\Filters::escapeHtmlText(date('Y')) /* line 2 */;
		echo ' Мій сайт</p>
</footer>';
	}
}
