<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: D:\kn24_php\kn24_php\src\templates\_nav.latte */
final class Template_fdb272ea6e extends Latte\Runtime\Template
{
	public const Source = 'D:\\kn24_php\\kn24_php\\src\\templates\\_nav.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<nav class="nav">
    <div class="nav-links">
        <a href="/" class="nav_link">Головна</a>
    </div>
    
    <div class="nav-links">
';
		if ($user) /* line 7 */ {
			echo '            <a href="/logout?token=';
			echo LR\Filters::escapeHtmlAttr($csrf_token) /* line 8 */;
			echo '" class="nav_link" 
               onclick="return confirm(\'Ви впевнені, що хочете вийти?\')">Logout</a>
';
		} else /* line 10 */ {
			echo '            <a href="/login" class="nav_link">Login</a>
';
		}
		echo '    </div>
</nav>  ';
	}
}
