<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: D:\kn24_php\kn24_php\src\Classes\..\templates\home.latte */
final class Template_075aa62995 extends Latte\Runtime\Template
{
	public const Source = 'D:\\kn24_php\\kn24_php\\src\\Classes\\..\\templates\\home.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '    <h1>Головна сторінка (файл src/templates/home.latte)</h1>
    <p>
        Привіт, ';
		echo LR\Filters::escapeHtmlText($user ?? 'Гість') /* line 3 */;
		echo '
    </p>

    <p>
        В файлі scripts/scriptAsync.js є код, що асинхронно додає картинку.
    </p>

    <button id="btn" class="btn-success">Додати картинку</button>
    
    <p>
        Картинка буде в цьому блоці &#8595;
    </p>

    <div id="div" class="card" style="list-style:none; display:flex; gap:1rem; flex-wrap:wrap; min-height:200px;">
        
    </div>

    <script src="./scripts/scriptAsync.js" defer></script>
';
	}
}
