<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: D:\kn24_php\kn24_php\src\Classes/../templates/home.latte */
final class Template_075aa62995 extends Latte\Runtime\Template
{
	public const Source = 'D:\\kn24_php\\kn24_php\\src\\Classes/../templates/home.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo 'Blablabla ';
		echo LR\Filters::escapeHtmlText($title) /* line 3 */;
	}
}
