<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: D:\kn24_php\kn24_php\src\Classes/../templates/home.latte */
final class Template_075aa62995 extends Latte\Runtime\Template
{
	public const Source = 'D:\\kn24_php\\kn24_php\\src\\Classes/../templates/home.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>';
		echo LR\Filters::escapeHtmlText($title ?? 'Сторінка') /* line 6 */;
		echo '</title>
    <link rel="stylesheet" href="./styles/style.css">

    <!-- Favicon базовий -->
    <link rel="icon" href="./images/icons/favicon.ico" sizes="any">

    <!-- PNG-іконки для браузерів -->
    <link rel="icon" type="image/png" sizes="16x16" href="./images/icons/favicon-16x16.png">
    <link rel="icon" type="image/png" sizes="32x32" href="./images/icons/favicon-32x32.png">

    <!-- Apple Touch Icon (для iOS / iPadOS) -->
    <link rel="apple-touch-icon" sizes="180x180" href="./images/icons/apple-touch-icon.png">

    <!-- Android / PWA -->
    <link rel="manifest" href="./images/icons/site.webmanifest">

    <!-- Тема і колір плитки для Windows -->
    <meta name="theme-color" content="#ffffff">
    <meta name="msapplication-TileColor" content="#ffffff">
</head>
<body>

';
		$this->createTemplate('nav.php', $this->params, 'include')->renderToContentType('html') /* line 28 */;
		echo '
    <h1>Головна сторінка (файл /pages/home.php)</h1>
    <p>
        Привіт, ';
		echo LR\Filters::escapeHtmlText($user ?? 'КОРИСТУВАЧ НЕ АВТОРИЗОВАНИЙ') /* line 32 */;
		echo '
    </p>

    <p>
        В файлі scripts/scriptAsync.js є код, що асинхронно додає картинку.
    </p>
    <button id="btn">Додати картинку.</button>
    
    <p>
        Картинка буде в цьому блоці &#8595;
    </p>
    <div id="div" style="list-style:none; display:flex; gap:10px; flex-wrap:wrap;">
        
    </div>

    <script src="./scripts/scriptAsync.js" defer></script>

</body>
</html>';
	}
}
