<?php

/** Generated by Latte 3.0.23 */

use Latte\Runtime as LR;

/** source: D:\kn24_php\kn24_php\src\Classes/../templates/@layout.latte */
final class Template_e574bfc217 extends Latte\Runtime\Template
{
	public const Source = 'D:\\kn24_php\\kn24_php\\src\\Classes/../templates/@layout.latte';


	public function main(array $ʟ_args): void
	{
		extract($ʟ_args);
		unset($ʟ_args);

		echo '<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <title>';
		echo LR\Filters::escapeHtmlText($title ?? 'Мій сайт') /* line 5 */;
		echo '</title>
    <link rel="stylesheet" href="./styles/style.css">

    <!-- Favicon базовий -->
    <link rel="icon" href="./images/icons/favicon.ico" sizes="any">

    <!-- PNG-іконки для браузерів -->
    <link rel="icon" type="image/png" sizes="16x16" href="./images/icons/favicon-16x16.png">
    <link rel="icon" type="image/png" sizes="32x32" href="./images/icons/favicon-32x32.png">

    <!-- Apple Touch Icon (для iOS / iPadOS) -->
    <link rel="apple-touch-icon" sizes="180x180" href="./images/icons/apple-touch-icon.png">

    <!-- Android / PWA -->
    <link rel="manifest" href="./images/icons/site.webmanifest">

    <!-- Тема і колір плитки для Windows -->
    <meta name="theme-color" content="#ffffff">
    <meta name="msapplication-TileColor" content="#ffffff">
</head>
<body>
';
		$this->createTemplate('_nav.latte', $this->params, 'include')->renderToContentType('html') /* line 26 */;
		echo '
    <main class="content">
';
		$this->createTemplate((LR\Helpers::stringOrNull($ʟ_tmp = $contentTemplate) ?? throw new InvalidArgumentException(sprintf('Template name must be a string, %s given.', get_debug_type($ʟ_tmp)))), $this->params, 'include')->renderToContentType('html') /* line 29 */;
		echo '    </main>

';
		$this->createTemplate('_footer.latte', $this->params, 'include')->renderToContentType('html') /* line 32 */;
		echo '</body>
</html>';
	}
}
